# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gcr.io/lightning-sandbox/lnd
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  restPort: 8080
  lightningPort: 9735
  rpcPort: 10009

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioningt
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 100Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 300m

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  lnd.conf: |-
    bitcoin.node=bitcoind
    bitcoind.rpchost=34.83.14.74
    bitcoind.rpcuser=rpcuser
    bitcoind.rpcpass=rpcpassword
    bitcoind.zmqpubrawblock=tcp://34.83.14.74:28332
    bitcoind.zmqpubrawtx=tcp://34.83.14.74:28333
    debuglevel=info
    bitcoin.active=1
    restlisten=0.0.0.0:8080
    rpclisten=0.0.0.0:10009
    listen=0.0.0.0:9735
    bitcoin.testnet=1
    tor.active=1
    tor.v3=1
    tor.privatekeypath=/root/.lnd/v3_onion_private_key
    alias=Lnd Test Helm
