apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "lnd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lnd.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.configurationFile }}
      initContainers:
        - name: copy-lnd-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/lnd.conf /root/.lnd/lnd.conf']
        - name: copy-lnd-unlock
          image: busybox
          command: ['sh', '-c', 'cp /configmap/unlock.txt /app/unlock.txt']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /root/.lnd/
            - name: unlock
              mountPath: /app/
      {{- end }}
      containers:
        - name: {{ template "lnd.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          ports:
            - name: lightning
              containerPort: {{ .Values.service.lightningPort }}
            - name: rest
              containerPort: {{ .Values.service.restPort }}
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
          volumeMounts:
            - name: data
              mountPath: /root
            - name: unlock
              mountPath: /app/unlock.txt
              subPath: unlock.txt
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /root/.lnd/lnd.conf
              subPath: lnd.conf
           {{- end }}
      volumes:
        {{- if .Values.configurationFile }}
        - name: config
          emptyDir: {}
        - name: unlock
          emptyDir: {}}
        - name: configmap
          configMap:
            name: {{ template "lnd.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "lnd.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
