apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - name: proxyrest
      port: {{ .Values.service.proxyRestPort }}
      targetPort: rest
    - name: lightning
      port: {{ .Values.service.lightningPort }}
      targetPort: lightning
    - name: proxyrpc
      port: {{ .Values.service.proxyRpcPort }}
      targetPort: rpc
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
