apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
    - name: lightning
      port: {{ .Values.service.lightningPort }}
      targetPort: lightning
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
